### ISSUE TITLE
Master branch dont have package.config in project

### ISSUE THREAD

**Issue by EtienneCollard** [sharpdx/SharpDX-Samples#26]
Is there another way to restore the NuGet package?

**Comment by xoofx** [comment]
Samples are no longer using NuGet packages, as nuget is really too much annoying when you want to synchronize the SharpDX repo with the samples repo. In order to use the samples, simply clone them in a directory (under for example a `Samples` directory) and download the binary SDK from http://sharpdx.org (they will be included in the github release binaries for an upcoming 3.0.0 update) and unzip them at the same level than the `Samples` directory, so that you will end-up with:
- a `Bin` directory containing `Desktop` and `StoreApp` sub directories
- a `Samples` directory containing a clone of the SharpDX-Samples repo
All samples should work with this layout. This is the same layout used when compiling SharpDX, so I don't have to maintain separates csproj files.
